### ISSUE TITLE
Issue installing with pip

### ISSUE THREAD

**Issue by gatordevin** [Unity-Technologies/pysolotools-fiftyone#11]
Hey everyone I'm having issues installing this package. Essentially it seems like pip is going through the version of every package in this project in order to find the ones that are compatible. Is there a way around this? For the most part it gets stuck in a recursive loop and I can't get it to download.

INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking

**Comment by StevenBorkman** [comment]
Hey @gatordevin, I have recently pushed some updates to the package. When you have an opportunity please check if this fixes your issues.

**Comment by gatordevin** [comment]
Hi, thank you so much the fix worked great! It now has another error. I will open a new issue topic for it.
